services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/test
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=admin
    volumes:
      - ./flyway/db-migrations:/flyway/sql
    command: -baselineOnMigrate=true migrate

  nginx:
    image: nginx:latest
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  db-data:
